### ISSUE TITLE
us-east-1 S3 is a special case

### ISSUE THREAD

**Issue by brianr2600** [kkb0318/irsa-manager#2]
To create buckets in us-east-1, you must omit the `LocationConstraint` field as specifying us-east-1 there produces an error. See https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucketConfiguration.html#API_CreateBucketConfiguration_Contents

Simply putting the bucket in another region doesn't seem to help - the S3 client hits the wrong endpoint and gets stuck in a redirect loop. As a workaround, I removed `CreateBucketConfiguration`  from interna/aws/aws.go. As expected it breaks every region _except_ us-east-1, so a proper patch is still needed.

**Comment by kkb0318** [comment]
@brianr2600 

Thank you for creating the issue!

I have resolved it with https://github.com/kkb0318/irsa-manager/pull/6.

I plan to release the fix along with the resolution for issue #2 in version 0.3.1. Please stay tuned for the upcoming release.
