### ISSUE TITLE
Add SESSION_TOKEN to aws-secret and pod environment

### ISSUE THREAD

**Issue by brianr2600** [kkb0318/irsa-manager#3]
In situations where the AWS credentials are provided via SSO, we need to add the AWS session token to the secret using `--from-literal=aws-session-token=` and then adjust the pod configuration to pass that part of the secret  through as `$AWS_SECRET_TOKEN`

(The use case here would be minikube running on a developer workstation where a time expired  limited privilege credential would be retrieved from `aws sso login ... ` or via the AWS webui).

**Comment by kkb0318** [comment]
@brianr2600 
Thank you for your first contribution! I clearly understand what you’re saying. 
I’ve added a few comments with some suggestions. 

I really appreciate your effort in improving this project.
